name: backend build

permissions:
  packages: write

on:
  push:
    tags:
      - 'qboxb/*'

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Get image tag from git tag
        id: image_tag
        run: echo "::set-output name=tagName::${{ github.ref_name }}" | tr '/' ':'

      - name: Send start message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Name: NekoQuestionBox
            Status: Build Start
            Tag: `${{ steps.image_tag.outputs.tagName }}`
            Url: https://github.com/LemonNekoGH/NekoQuestionBox
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get image tag from git tag
        id: image_tag
        run: echo "::set-output name=tagName::${{ github.ref_name }}" | tr '/' ':'

      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./be
          tags: |
            ghcr.io/lemonnekogh/${{ steps.image_tag.outputs.tagName }}
            ghcr.io/lemonnekogh/qboxb:latest

      - name: Send end message to telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          format: markdown
          message: |
            GitHub Actions Start
            Name: NekoQuestionBox
            Status: Build End
            Tag: `${{ steps.image_tag.outputs.tagName }}`
            Url: https://github.com/LemonNekoGH/NekoQuestionBox
