name: unittest
on:
  pull_request:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      # checkout code
      - uses: actions/checkout@v3
      # set up go
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.18.0"
      # Scan for protential mistakes
      - name: Vet
        run: |
          go vet ./...
      - name: Unit tests
        id: test
        run: |
          go test $(go list ./...) -coverprofile coverage.txt -covermode atomic -p=1
          go tool cover -func coverage.txt

      # Codecov
      - uses: codecov/codecov-action@v2
